name: paginate_firestore
description: A flutter package to simplify pagination with firestore data.
version: 1.0.3
homepage: https://github.com/excogitatr/paginate_firestore
issue_tracker: https://github.com/excogitatr/paginate_firestore/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  cloud_firestore: ^1.0.3
  provider: ^5.0.0
=======
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  cloud_firestore: ^3.1.0
  provider: ^6.0.1
>>>>>>> 65064c3699d5d00ebfc49caa89f39aca79a821d4

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
